[build]
  publish = "_site/"
  command = "npm run build && npm run test"  # Only publish if tests pass
[[redirects]]
  from = "/friends"
  to = "/blogroll"
[[redirects]]
  from = "/2019/05/26/i-can-see-your-local-web-servers"
  to = "http://http.jameshfisher.com/2019/05/26/i-can-see-your-local-web-servers"
[[redirects]]
  from = "/2018/07/29/month-of-tigyog"
  to = "/2018/07/29/month-of-jack-robinson"